* learn-clojure
  :PROPERTIES:
  :CUSTOM_ID: learn-clojure
  :END:

A breadcrumb trail of Clojure related learning resources.

** Prerequisite Learning
   :PROPERTIES:
   :CUSTOM_ID: prerequisite-learning
   :END:

Every modern system comes with a shell program. The shell is a program
which allows the user to initiate, monitor and manage the running of
other programs on the system. The system's files and directories can
also be managed from the shell.

A big part of programming is making sure the right files, with the right
contents are located in the right places within your computer's
file-system.

At first, you can get by with learning the bare minimum or even nothing
at all about working in the shell and still make progress in your
learning path. There's nothing wrong with manipulating files and
directories in your system's Graphical User Interface (GUI), especially
if that's what you already know. However, a lot of documentation on the
web will assume you know how to operate a shell. The earliest versions
of this documentation assume this too. In time we will create a path for
non-shell users.

If you've never used the shell, please first go through the
[[https://tutorial.djangogirls.org/en/intro_to_command_line/][Intro to Command Line]] tutorial at the Django Girls site. This tutorial was
chosen because it covers just enough material to get you started without
distracting you with excessive detail. It also provides separate
instructions for Linux, OS X, and Windows systems. If you are a Windows
user, please go through the tutorial once and learn the built-in Windows
commands and then repeat the tutorial after reading the note below to
Windows users and installing Babun. On your second time through, follow
the instructions for Linux shell commands. Many web docs ignore Windows
users. Achieving this small goal will pay off big for you over time by
being able to follow many online docs written for Linux users.

Now you're ready to start learning some Clojure, but if you curious to
learn more about working from the command line, a.k.a. the shell, you
might enjoy the [[http://linuxcommand.org/index.php][Linux Command]] site.

Proceed to the section below [[#learning-paths]].

** A note to Windows users
   :PROPERTIES:
   :CUSTOM_ID: a-note-to-windows-users
   :END:

In order to simplify this training material for both writers and
readers, we assume that you are using bash or zsh with standard tools
such as git, grep, wget, curl, etc. The best way to achieve this on a
Windows machine is to install and use
[[http://babun.github.io/][Babun]]. For more details on installing
Babun, please see the freely available video series
/[[https://youtu.be/rl7PzPAZDyY][Command Line Power User]]/ by Wes Bos.

** Learning Paths
   :PROPERTIES:
   :CUSTOM_ID: learning-paths
   :END:

No two learners are exactly alike. Nonetheless we will strive to
categorize learners in a general way to help you pick the path forward
that best matches your present circumstance.
